#!/bin/bash
export LANG="en_US.UTF-8"

cd /root/check-duplicate/scripts
nohup gunicorn -w 8 -b0.0.0.0:8088 check_duplicate:app >> /root/check-duplicate/check-duplicate.log &

tail -f /root/check-duplicate/check-duplicate.log